version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  add-post:
    lang: golang-middleware
    handler: ./add-post
    image: alexellis2/add-post:0.1.0
    environment:
      GITHUB_REPO: git@github.com:wilsonianb/kubecon-blog.git
      GITHUB_USER: wilsonianb
    build_args:
      GO111MODULE: on
    secrets:
      - blog-secrets
    environment:
      write_debug: true
      SSH_KNOWN_HOSTS: /home/app/known_hosts
  blog:
    lang: hugo
    handler: ./blog
    image: alexellis2/blog:latest
    environment:
      write_debug: true
