name = "Webmonetization"
license = "MIT"
licenselink = "https://github.com/sabinebertram/hugo-webmonetization-component/blob/master/LICENSE"
description = "Hugo theme component with the 'webmonetization' partial enabling web monetization."
homepage = "https://github.com/sabinebertram/hugo-webmonetization-component"
tags = ["webmonetization", "interledger"]
features = ["webmonetization"]
min_version = "0.55.0"

[author]
    name = "Sabine Bertram"
    homepage = "https://github.com/sabinebertram"